# Site settings
title: Pengin Blog
email: rory@pengin.pro
description: > # this means to ignore newlines until "baseurl:"
  Blog about stuff mostly related to technology, development, science
  sometimes games, music and other stuff i'm interested in.
  Hopefully some of it is useful to you too....
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.pengin.pro" # the base hostname & protocol for your site
twitter_username: rory80hz
github_username:  rory80hz

# Build settings
markdown: kramdown
